// export default ALL_PRODUCTS_REQUEST = 'ALL_PRODUCT_REQUEST'
// export default ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
// export default ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL'

// export default CLEAR_ERRORS = 'CLEAR_ERRORS'

const Object = {
    ALL_PRODUCTS_REQUEST: 'ALL_PRODUCT_REQUEST',
    ALL_PRODUCTS_SUCCESS: 'ALL_PRODUCTS_SUCCESS',
    ALL_PRODUCTS_FAIL: 'ALL_PRODUCTS_FAIL',
    CLEAR_ERRORS: 'CLEAR_ERRORS'
}

module.exports = Object;